seeds_advertisement/seeds/urls.py
from django.urls import path

from . import views

app_name = 'seeds_advertisement'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('advertisements/<int:advertisement_id>/', views.advertisements_detail_view, name='advertisements_detail'),
    path('advertisements/', views.advertisements_view, name='advertisements'),
    path('farmers/', views.farmers_view, name='farmers'),
]

seeds_advertisement/seeds_advertisement/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('seeds.urls')),
    path('admin/', admin.site.urls),
]

seeds_advertisement/seeds/models.py
import datetime
from django.db import models
from django.core.validators import MaxValueValidator
from django.utils import timezone
from enum import Enum


class RegionChoice(Enum):
    Kayes = "Kayes"
    Koulikoro = "Koulikoro"
    Bamako = "Bamako"
    Sikasso = "Sikasso"
    Segou = "Ségou"
    Mopti = "Mopti"
    Tombouctou = "Tombouctou"
    Gao = "Gao"
    Kidal = "Kidal"


class Farmer(models.Model):
    phone_number = models.CharField(primary_key=True, max_length=9)
    full_name = models.CharField(max_length=70)
    region = models.CharField(
      max_length=10,
      choices=[(tag.name, tag.value) for tag in RegionChoice]
    )
    place = models.CharField(max_length=200)

    def __str__(self):
        return self.full_name


class Advertisement(models.Model):
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE)
    seed = models.CharField(max_length=200)
    seed_type = models.CharField(max_length=200)
    description = models.TextField(default="", blank=True)
    quantity = models.PositiveIntegerField(validators=[MaxValueValidator(99999)])
    price = models.PositiveIntegerField(validators=[MaxValueValidator(999999999)])
    pub_date = models.DateTimeField('date published')

    class Meta:
        unique_together = (('farmer', 'pub_date'),)
        unique_together = (('farmer', 'seed_type'),)

    def __str__(self):
        return self.seed + " - " + self.seed_type

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

# Add new instances through python shell
# f = Farmer(phone_number="098583850", full_name="Mariam Issa", region=RegionChoice.Mopti, place="Commerce")
# a = Advertisement(farmer=f, seed ="Maize",seed_type ="Sotubaka", description="", quantity="492", price="340", pub_date=timezone.now())

seeds_advertisement/seeds/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from django.http import Http404

from .models import Farmer, Advertisement


def index_view(request):
    advertisements_count = Advertisement.objects.count()
    farmers_count = Farmer.objects.count()
    context = {
        'advertisements_count': advertisements_count,
        'farmers_count': farmers_count,
    }
    return render(request, 'seeds/index.html', context)


def advertisements_view(request):
    advertisement_list = Advertisement.objects.order_by('-farmer').order_by('-pub_date')
    context = {
        'advertisement_list': advertisement_list,
    }
    return render(request, 'seeds/advertisements.html', context)


def advertisements_detail_view(request, advertisement_id):
    advertisement = get_object_or_404(Advertisement, pk=advertisement_id)
    return render(request, 'seeds/advertisements_detail.html', {'advertisement': advertisement})


def farmers_view(request):
    farmer_list = Farmer.objects.order_by('-full_name')
    context = {
        'farmer_list': farmer_list,
    }
    return render(request, 'seeds/farmers.html', context)

seeds_advertisement/seeds/templates/seeds/advertisements.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'seeds/style.css' %}" />

<h2>LIST OF ALL ADVERTISEMENTS</h2>

{% if advertisement_list %}
    <div>
    {% for advertisement in advertisement_list %}
        <div><a href="{% url 'seeds_advertisement:advertisements' %}{{ advertisement.id }}/">{{ advertisement.seed }} - {{advertisement.seed_type }} ({{advertisement.farmer }})</a></div>
    {% endfor %}
    </div>
{% else %}
    <p>There are no advertisements available.</p>
{% endif %}

seeds_advertisement/seeds/templates/seeds/advertisements_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'seeds/style.css' %}" />

<h2>ADVERTISEMENT DETAIL</h2>

<p><b>Seed: </b>{{ advertisement.seed }}</p>
<p><b>Seed type: </b>{{ advertisement.seed_type }}</p>
{% if advertisement.description %}
    <p><b>Description: </b>{{ advertisement.description }}</p>
{% endif %}
<p><b>Quantity: </b>{{ advertisement.quantity }} KG</p>
<p><b>Price: </b>{{ advertisement.price }} CFA/Kg</p>
<p><b>Farmer: </b>{{ advertisement.farmer }}</p>
<p><b>Last modified date: </b>{{ advertisement.pub_date }}</p>

seeds_advertisement/seeds/templates/seeds/farmers.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'seeds/style.css' %}" />

<h2>LIST OF ALL FARMERS</h2>

{% if farmer_list %}
    <div>
    {% for farmer in farmer_list %}
        <div class="background_farmer">
            <p><b>Name: </b>{{ farmer.full_name }}</p>
            <p><b>Phone number: </b>{{ farmer.phone_number }}</p>
            <p><b>Region: </b>{{ farmer.region }}</p>
            <p><b>Place: </b>{{ farmer.place }}</p>
           </div>
    {% endfor %}
    </div>
{% else %}
    <p>There are no farmers available.</p>
{% endif %}

seeds_advertisement/seeds/templates/seeds/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'seeds/style.css' %}" />

<h1>MALI SEED ADVERTISEMENTS</h1>

<h2>{{ advertisements_count }}  advertisements are available</h2>
<a href="{% url 'seeds_advertisement:advertisements' %}">Go to advertisements list </a>

<h2>{{ farmers_count }} farmers are active</h2>
<a href="{% url 'seeds_advertisement:farmers' %}">Go to farmers list </a>